sudo: required
dist: trusty

matrix:
    include:
        - compiler: gcc
          addons:
              apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - boost-latest
                packages:
                    - g++-4.9
          env: COMPILER=g++-4.9

before_script:
    # setup environment
    - sudo -H sh ./script/installation/packages.sh
    - pip install --user cpp-coveralls

script:
    # first, run validator
    - python ./script/validators/validator.py
      # build
    - mkdir build
    - cd build
    - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
    - make
    - make check
    - make coveralls

