language: cpp
compiler:
    - g++

install:
    # get c++11 support
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - gcc-4.8
            - g++-4.8

before_script:
    # setup environment
    - sudo -H sh ./script/installation/packages.sh

script:
    # first, run validator
    - python ./scripts/validators/validator.py
    # build
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release
    - make
    - make check
